import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inknut_Antiqua } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";

import { getServerSession } from "next-auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inknut = Inknut_Antiqua({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inknut",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Idea Star",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en" className={inknut.className}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased ${inter.className}`}>
          {children}
      </body>
    </html>
  );
}